name: Merge Article Schedule
on:
  pull_request:
    types:
      - opened
      - edited
  schedule:
    # 5AM UTC => 10:30AM IST
    - cron: '0 5 * * *'

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:
      - uses: gr2m/merge-schedule-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
